# Generated by Django 3.1.3 on 2020-11-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
