# Generated by Django 3.1.3 on 2020-11-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_categoriapai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoriaPai',
        ),
    ]
