# Generated by Django 3.1.3 on 2020-11-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_remove_categoria_categoriapai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
