# Generated by Django 3.1.3 on 2020-11-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_auto_20201112_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='produtosAssociados',
            field=models.IntegerField(default=0),
        ),
    ]
