# Generated by Django 3.1.3 on 2020-11-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_categoria_produtosassociados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produtosAssociados',
        ),
    ]
