# Generated by Django 3.1.3 on 2020-11-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0006_remove_categoria_produtosassociados'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
