# Generated by Django 3.1.3 on 2020-11-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0007_auto_20201125_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
