# Generated by Django 3.1.3 on 2020-11-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=89.9, max_digits=5),
        ),
    ]
