# Generated by Django 3.1.3 on 2020-11-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20201112_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='secao',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
