# Generated by Django 3.1.3 on 2020-11-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_categoriapai'),
        ('produto', '0004_auto_20201112_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(to='categoria.Categoria'),
        ),
    ]
