# Generated by Django 3.1.3 on 2020-11-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_vendidopor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='vendidoPor',
        ),
        migrations.AddField(
            model_name='produto',
            name='logoLoja',
            field=models.SlugField(default='candyStore', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.SlugField(default='Candy Store', max_length=100),
        ),
    ]
