# Generated by Django 3.1.3 on 2020-11-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20201112_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida elit nec sapien interdum sagittis. Nulla dignissim erat eu mauris dignissim, ac vestibulum est laoreet. Phasellus sapien metus, cursus a tempus at, viverra laoreet sapien. Donec ullamcorper sit amet nibh eget aliquam. Donec sodales mattis orci, ut consequat tortor pretium eu. Pellentesque tincidunt, nunc non condimentum mattis, metus risus dignissim lacus, at consequat justo odio sit amet dui. Proin sed ultricies nunc. \nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida elit nec sapien interdum sagittis. Nulla dignissim erat eu mauris dignissim, ac vestibulum est laoreet. Phasellus sapien metus, cursus a tempus at, viverra laoreet sapien. Donec ullamcorper sit amet nibh eget aliquam. Donec sodales mattis orci, ut consequat tortor pretium eu. Pellentesque tincidunt, nunc non condimentum mattis, metus risus dignissim lacus, at consequat justo odio sit amet dui. Cras ut metus eleifend est ultricies aliquam vel sit amet ante. In dignissim pellentesque suscipit. Vivamus at nisi dapibus, accumsan neque in, consectetur nunc. Nam efficitur ex faucibus, imperdiet ex eget, vehicula purus. Donec commodo sagittis hendrerit.', max_length=1500),
        ),
    ]
