# Generated by Django 3.1.3 on 2020-11-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_auto_20201112_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtdEstoque',
            new_name='estoque',
        ),
    ]
