# Generated by Django 3.1.3 on 2020-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_auto_20201121_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
    ]
