# Generated by Django 3.1.3 on 2020-11-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_produto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(max_length=80),
        ),
    ]
