# Generated by Django 3.1.3 on 2020-11-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_auto_20201121_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
